### PR TITLE
Published module now compiled JSX

### PR DESCRIPTION
**Pull request by cymen**
- use 'jsx --harmony' to compile (run `npm run build`)
- remove all of the unused files
- sourcemaps and other concerns handled by consumer
- remove example (I suggest making a react-progress-example, put a webpack config in there and have it pull in this module and use it -- then point README to there)

### CODE REVIEW

**Comment by cymen** [comment]
@cezary This is similar to the other PR except `lib/react-progress.js` is untouched -- the Harmony string interpolation remains along with JSX. I can make the example if you want but I think it would be much cleaner to do that in a separate repo.

**Comment by cezary** [comment]
Nice! Much simpler project layout, thanks! I think I'll keep the demo in the gh-pages branch.

**Comment by cymen** [comment]
@cezary Thanks for merging! I bumped the version to 0.0.3 so if you get the time to do an npm publish, that would be awesome (I'm using this in a project). Thanks for the module.

**Comment by cezary** [comment]
You're welcome, published.

**Pull request merged**
